SELECT 'START DEFAULT ORDER/ORDER_ITEM QUERY', `current_timestamp`();
-- Normal Tables
SELECT
    ORDER_ID
  , USER_ID
  , COUNT(PRODUCT_ID)
  , SUM(QUANTITY * COST)
FROM
    ORDER_${FILE_TYPE}
        JOIN ORDER_ITEM_${FILE_TYPE}
            ON ORDER_${FILE_TYPE}.ID = ORDER_ITEM_${FILE_TYPE}.ORDER_ID
WHERE
    QUANTITY > 5
GROUP BY
    ORDER_ID, USER_ID
LIMIT 10;
SELECT 'END DEFAULT ORDER/ORDER_ITEM QUERY', `current_timestamp`();

SELECT 'START SMALL-FILE ORDER/ORDER_ITEM QUERY', `current_timestamp`();
-- Small File Tables
SELECT
    ORDER_ID
  , USER_ID
  , COUNT(PRODUCT_ID)
  , SUM(QUANTITY * COST)
FROM
    ORDER_SMALL_${FILE_TYPE}
        JOIN ORDER_ITEM_SMALL_${FILE_TYPE}
            ON ORDER_SMALL_${FILE_TYPE}.ID = ORDER_ITEM_SMALL_${FILE_TYPE}.ORDER_ID
WHERE
    QUANTITY > 5
GROUP BY
    ORDER_ID, USER_ID
LIMIT 10;
SELECT 'END SMALL-FILE ORDER/ORDER_ITEM QUERY', `current_timestamp`();
